<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $permissions = [
            'dom-dashboard'                         => 'DoM Dashboard',
            'flagged-items-dashboard'               => 'Inspection Dashboard',
            'document-dashboard'                    => 'Document Dashboard',
            'monthly-report-dom-checklists'         => 'Monthly Reports',
            'dom-dashboard-2'                       => 'DoM Dashboard V2',
            'dom-dashboard-2-specific-store'        => 'DoM Dashboard V2 Specific Store',

            'users.index'                           => 'View Users',
            'users.create'                          => 'Create User',
            'users.store'                           => 'Save User',
            'users.show'                            => 'Show User',
            'users.edit'                            => 'Edit User',
            'users.update'                          => 'Update User',
            'users.destroy'                         => 'Delete User',
            'users.import'                          => 'Import Users',
            'users.export'                          => 'Export Users',

            'roles.index'                           => 'View Roles',
            'roles.create'                          => 'Create Role',
            'roles.store'                           => 'Save Role',
            'roles.show'                            => 'Show Role',
            'roles.edit'                            => 'Edit Role',
            'roles.update'                          => 'Update Role',
            'roles.destroy'                         => 'Delete Role',

            'store-types.index'                     => 'View Store Types',
            'store-types.create'                    => 'Create Store Type',
            'store-types.store'                     => 'Save Store Type',
            'store-types.show'                      => 'Show Store Type',
            'store-types.edit'                      => 'Edit Store Type',
            'store-types.update'                    => 'Update Store Type',
            'store-types.destroy'                   => 'Delete Store Type',

            'model-types.index'                     => 'View Model Types',
            'model-types.create'                    => 'Create Model Type',
            'model-types.store'                     => 'Save Model Type',
            'model-types.show'                      => 'Show Model Type',
            'model-types.edit'                      => 'Edit Model Type',
            'model-types.update'                    => 'Update Model Type',
            'model-types.destroy'                   => 'Delete Model Type',

            'stores.index'                          => 'View Stores',
            'stores.create'                         => 'Create Store',
            'stores.store'                          => 'Save Store',
            'stores.show'                           => 'Show Store',
            'stores.edit'                           => 'Edit Store',
            'stores.update'                         => 'Update Store',
            'stores.destroy'                        => 'Delete Store',

            'store-categories.index'                => 'View Store Categories',
            'store-categories.create'               => 'Create Store Category',
            'store-categories.store'                => 'Save Store Category',
            'store-categories.show'                 => 'Show Store Category',
            'store-categories.edit'                 => 'Edit Store Category',
            'store-categories.update'               => 'Update Store Category',
            'store-categories.destroy'              => 'Delete Store Category',

            'assets-types.index'                    => 'View Asset Types',
            'assets-types.create'                   => 'Create Asset Type',
            'assets-types.store'                    => 'Save Asset Type',
            'assets-types.show'                     => 'Show Asset Type',
            'assets-types.edit'                     => 'Edit Asset Type',
            'assets-types.update'                   => 'Update Asset Type',
            'assets-types.destroy'                  => 'Delete Asset Type',

            'assets-makes.index'                    => 'View Asset Makes',
            'assets-makes.create'                   => 'Create Asset Make',
            'assets-makes.store'                    => 'Save Asset Make',
            'assets-makes.show'                     => 'Show Asset Make',
            'assets-makes.edit'                     => 'Edit Asset Make',
            'assets-makes.update'                   => 'Update Asset Make',
            'assets-makes.destroy'                  => 'Delete Asset Make',

            'assets.index'                          => 'View Assets',
            'assets.create'                         => 'Create Asset',
            'assets.store'                          => 'Save Asset',
            'assets.show'                           => 'Show Asset',
            'assets.edit'                           => 'Edit Asset',
            'assets.update'                         => 'Update Asset',
            'assets.destroy'                        => 'Delete Asset',

            'assets-categories.index'               => 'View Asset Categories',
            'assets-categories.create'              => 'Create Asset Category',
            'assets-categories.store'               => 'Save Asset Category',
            'assets-categories.show'                => 'Show Asset Category',
            'assets-categories.edit'                => 'Edit Asset Category',
            'assets-categories.update'              => 'Update Asset Category',
            'assets-categories.destroy'             => 'Delete Asset Category',

            'asset-statuses.index'                  => 'View Asset Statuses',
            'asset-statuses.create'                 => 'Create Asset Status',
            'asset-statuses.store'                  => 'Save Asset Status',
            'asset-statuses.show'                   => 'Show Asset Status',
            'asset-statuses.edit'                   => 'Edit Asset Status',
            'asset-statuses.update'                 => 'Update Asset Status',

            'corporate-office.index'                => 'View Corporate Offices',
            'corporate-office.create'               => 'Create Corporate Office',
            'corporate-office.store'                => 'Save Corporate Office',
            'corporate-office.show'                 => 'Show Corporate Office',
            'corporate-office.edit'                 => 'Edit Corporate Office',
            'corporate-office.update'               => 'Update Corporate Office',
            'corporate-office.destroy'              => 'Delete Corporate Office',

            'departments.index'                     => 'View Departments',
            'departments.create'                    => 'Create Department',
            'departments.store'                     => 'Save Department',
            'departments.show'                      => 'Show Department',
            'departments.edit'                      => 'Edit Department',
            'departments.update'                    => 'Update Department',
            'departments.destroy'                   => 'Delete Department',

            'checklists.index'                      => 'View Checklist Templates',
            'checklists.create'                     => 'Create Checklist Template',
            'checklists.store'                      => 'Save Checklist Template',
            'checklists.show'                       => 'Show Checklist Template',
            'checklists.edit'                       => 'Edit Checklist Template',
            'checklists.update'                     => 'Update Checklist Template',
            'checklists.destroy'                    => 'Delete Checklist Template',
            'duplicate-checklist'                   => 'Duplicate Checklist Template',
            'import.scheduling'                     => 'Import Scheduling',
            'multi-checklist-import'                => 'Import Multiple Scheduling',
            'store-multi-checklist-import'          => 'Import Store Multi Checklist',

            'checklist-scheduling.index'            => 'View Checklist Schedulings',
            'checklist-scheduling.create'           => 'Create Checklist Schedule',
            'checklist-scheduling.store'            => 'Save Checklist Schedule',
            'checklist-scheduling.show'             => 'Show Checklist Schedule',
            'checklist-scheduling.edit'             => 'Edit Checklist Schedule',
            'checklist-scheduling.update'           => 'Update Checklist Schedule',
            'checklist-scheduling.destroy'          => 'Delete Checklist Schedule',

            'pass-verifications.index'              => 'View Pass Verifications',

            'tat-overview.index'                    => 'View TAT Overview',

            'scheduled-tasks.index'                 => 'View Scheduled Tasks',
            'scheduled-tasks.create'                => 'Create Scheduled Task',
            'scheduled-tasks.store'                 => 'Save Scheduled Task',
            'scheduled-tasks.show'                  => 'Show Scheduled Task',
            'scheduled-tasks.edit'                  => 'Edit Scheduled Task',
            'scheduled-tasks.update'                => 'Update Scheduled Task',
            'scheduled-tasks.destroy'               => 'Delete Scheduled Task',
            'scheduled-tasks.bulk-delete'           => 'Bulk Delete Scheduled Tasks',
            'scheduled-tasks-change-date-time'      => 'Change Task Date & Time',
            'reschedule-task'                       => 'Reschedule Task',
            'cancel-task'                           => 'Cancel Task',
            'reschedules'                           => 'View Rescheduled Tasks',
            'task-checkers'                         => 'Map Checkers to Task',
            'task-log'                              => 'View Task Log',
            'task-export-excel'                     => 'Export Task to Excel',
            'task-export-pdf'                       => 'Export Task to PDF',
            'task-export-compressed-pdf'            => 'Export Task to Compressed PDF',
            'checklists-submission'                 => 'Submit Checklist',
            'checklists-submission-view'            => 'View Checklist Submission',
            'checklists-submission-view-for-maker'  => 'View Checklist Submission (Maker)',
            'checklists-submission-view-for-checker'=> 'View Checklist Submission (Checker)',
            'checker-submisison'                    => 'View Checker Submission',
            'checklists-submission-comparison'      => 'View Checklist Side-by-Side Comparison',
            'compare-checklist'                     => 'Compare Checklists',
            'export-comparison'                     => 'Export Checklist Comparison',
            'imported-schedulings-history'          => 'View CSV Import History',

            'workflow-checklists.index'             => 'View Workflow Checklists',
            'workflow-checklists.create'            => 'Create Workflow Checklist',
            'workflow-checklists.store'             => 'Save Workflow Checklist',
            'workflow-checklists.show'              => 'Show Workflow Checklist',
            'workflow-checklists.edit'              => 'Edit Workflow Checklist',
            'workflow-checklists.update'            => 'Update Workflow Checklist',
            'workflow-checklists.destroy'           => 'Delete Workflow Checklist',
            'workflow-duplicate-checklist'          => 'Duplicate Workflow Checklist',

            'workflow-templates.index'              => 'View Workflow Templates',
            'workflow-templates.create'             => 'Create Workflow Template',
            'workflow-templates.store'              => 'Save Workflow Template',
            'workflow-templates.show'               => 'Show Workflow Template',
            'workflow-templates.edit'               => 'Edit Workflow Template',
            'workflow-templates.update'             => 'Update Workflow Template',
            'workflow-templates.destroy'            => 'Delete Workflow Template',
            'workflow-templates.import'             => 'Import Workflow Templates',
            'workflow-templates.download-template'  => 'Download Workflow Template File',

            'workflow-assignments.index'            => 'View Workflow Assignments',
            'workflow-assignments.create'           => 'Create Workflow Assignment',
            'workflow-assignments.store'            => 'Save Workflow Assignment',
            'workflow-assignments.show'             => 'Show Workflow Assignment',
            'workflow-assignments.edit'             => 'Edit Workflow Assignment',
            'workflow-assignments.update'           => 'Update Workflow Assignment',
            'workflow-assignments.destroy'          => 'Delete Workflow Assignment',
            'workflow-assignments.export-excel'     => 'Export Workflow Assignment to Excel',
            'workflow-assignments.export-pdf'       => 'Export Workflow Assignment to PDF',
            'workflow-task-export-excel'            => 'Export Workflow Task to Excel',
            'workflow-task-export-pdf'              => 'Export Workflow Task to PDF',
            'workflow-task-export-compressed-pdf'   => 'Export Workflow Task to Compressed PDF',

            'workflow-tasks.index'                  => 'View Workflow Tasks',
            'workflow-tasks.create'                 => 'Create Workflow Task',
            'workflow-tasks.store'                  => 'Save Workflow Task',
            'workflow-tasks.show'                   => 'Show Workflow Task',
            'workflow-tasks.edit'                   => 'Edit Workflow Task',
            'workflow-tasks.update'                 => 'Update Workflow Task',
            'workflow-tasks.destroy'                => 'Delete Workflow Task',
            'workflow-tasks.bulk-delete'            => 'Bulk Delete Workflow Tasks',
            'workflow-tasks.submission-view'        => 'View Workflow Task Submission',
            'workflow.checklists-submission-comparison'      => 'View Workflow Checklist Side-by-Side Comparison',
            'workflow.checklists-submission-view-for-maker'  => 'View Workflow Checklist Submission (Maker)',
            'workflow.checklists-submission-view-for-checker'=> 'View Workflow Checklist Submission (Checker)',

            'topics.index'                          => 'View LMS Categories',
            'topics.create'                         => 'Create LMS Category',
            'topics.store'                          => 'Save LMS Category',
            'topics.show'                           => 'Show LMS Category',
            'topics.edit'                           => 'Edit LMS Category',
            'topics.update'                         => 'Update LMS Category',
            'topics.destroy'                        => 'Delete LMS Category',

            'contents.index'                        => 'View LMS Contents',
            'contents.create'                       => 'Create LMS Content',
            'contents.store'                        => 'Save LMS Content',
            'contents.show'                         => 'Show LMS Content',
            'contents.edit'                         => 'Edit LMS Content',
            'contents.update'                       => 'Update LMS Content',
            'contents.destroy'                      => 'Delete LMS Content',
            'content-analytics'                     => 'View LMS Content Analytics',

            'notification-templates.index'          => 'View Notification Templates',
            'notification-templates.create'         => 'Create Notification Template',
            'notification-templates.store'          => 'Save Notification Template',
            'notification-templates.show'           => 'Show Notification Template',
            'notification-templates.edit'           => 'Edit Notification Template',
            'notification-templates.update'         => 'Update Notification Template',
            'notification-templates.destroy'        => 'Delete Notification Template',
            'notification-center'                   => 'View System Notifications',

            'settings.edit'                         => 'Edit Settings',
            'settings.update'                       => 'Update Settings',

            'documents.index'                       => 'View Document Types',
            'documents.create'                      => 'Create Document Type',
            'documents.store'                       => 'Save Document Type',
            'documents.show'                        => 'Show Document Type',
            'documents.edit'                        => 'Edit Document Type',
            'documents.update'                      => 'Update Document Type',
            'documents.destroy'                     => 'Delete Document Type',

            'document-upload.index'                 => 'View Document Uploads',
            'document-upload.create'                => 'Create Document Upload',
            'document-upload.store'                 => 'Save Document Upload',
            'document-upload.show'                  => 'Show Document Upload',
            'document-upload.edit'                  => 'Edit Document Upload',
            'document-upload.update'                => 'Update Document Upload',
            'document-upload.destroy'               => 'Delete Document Upload',
            'document-upload.import'                => 'Import Documents',
            'document-upload.export'                => 'Export Documents',

            'particulars.index'                     => 'View Particulars',
            'particulars.create'                    => 'Create Particular',
            'particulars.store'                     => 'Save Particular',
            'particulars.show'                      => 'Show Particular',
            'particulars.edit'                      => 'Edit Particular',
            'particulars.update'                    => 'Update Particular',
            'particulars.destroy'                   => 'Delete Particular',

            'issues.index'                          => 'View Issues',
            'issues.create'                         => 'Create Issue',
            'issues.store'                          => 'Save Issue',
            'issues.show'                           => 'Show Issue',
            'issues.edit'                           => 'Edit Issue',
            'issues.update'                         => 'Update Issue',
            'issues.destroy'                        => 'Delete Issue',

            'ticket-management.index'               => 'View Tickets',
            'ticket-management.create'              => 'Create Ticket',
            'ticket-management.store'               => 'Save Ticket',
            'ticket-management.show'                => 'Show Ticket',
            'ticket-management.edit'                => 'Edit Ticket',
            'ticket-management.update'              => 'Update Ticket',
            'ticket-management.accept'              => 'Accept Ticket',
            'ticket-management.reopen'              => 'Reopen Ticket',
            'ticket-management.export'              => 'Export Tickets',

            'ticket-escalations.index'              => 'View Ticket Escalations',
            'ticket-escalations.create'             => 'Create Ticket Escalation',
            'ticket-escalations.store'              => 'Save Ticket Escalation',
            'ticket-escalations.view'               => 'Show Ticket Escalation',
            'ticket-escalations.edit'               => 'Edit Ticket Escalation',
            'ticket-escalations.update'             => 'Update Ticket Escalation',
            'ticket-escalations.destroy'            => 'Delete Ticket Escalation',

            'menu.categories.index'                 => 'View Menu Categories',
            'menu.categories.create'                => 'Create Menu Category',
            'menu.categories.store'                 => 'Save Menu Category',
            'menu.categories.edit'                  => 'Edit Menu Category',
            'menu.categories.update'                => 'Update Menu Category',
            'menu.categories.destroy'               => 'Delete Menu Category',
            'menu.categories.restore'               => 'Restore Menu Category',

            'menu.attributes.index'                 => 'View Menu Attributes',
            'menu.attributes.create'                => 'Create Menu Attribute',
            'menu.attributes.store'                 => 'Save Menu Attribute',
            'menu.attributes.edit'                  => 'Edit Menu Attribute',
            'menu.attributes.update'                => 'Update Menu Attribute',
            'menu.attributes.destroy'               => 'Delete Menu Attribute',
            'menu.attributes.restore'               => 'Restore Menu Attribute',

            'menu.addons.index'                     => 'View Menu Add-ons',
            'menu.addons.create'                    => 'Create Menu Add-on',
            'menu.addons.store'                     => 'Save Menu Add-on',
            'menu.addons.edit'                      => 'Edit Menu Add-on',
            'menu.addons.update'                    => 'Update Menu Add-on',
            'menu.addons.destroy'                   => 'Delete Menu Add-on',
            'menu.addons.restore'                   => 'Restore Menu Add-on',

            'menu.products.index'                   => 'View Menu Products',
            'menu.products.create'                  => 'Create Menu Product',
            'menu.products.store'                   => 'Save Menu Product',
            'menu.products.edit'                    => 'Edit Menu Product',
            'menu.products.update'                  => 'Update Menu Product',
            'menu.products.destroy'                 => 'Delete Menu Product',
            'menu.products.restore'                 => 'Restore Menu Product',

            'menu.promotions.index'                 => 'View Menu Promotions',
            'menu.promotions.create'                => 'Create Menu Promotion',
            'menu.promotions.store'                 => 'Save Menu Promotion',
            'menu.promotions.edit'                  => 'Edit Menu Promotion',
            'menu.promotions.update'                => 'Update Menu Promotion',
            'menu.promotions.destroy'               => 'Delete Menu Promotion',
            'menu.promotions.restore'               => 'Restore Menu Promotion',

            'menu.orders.index'                     => 'View Menu Orders',
            'menu.orders.create'                    => 'Create Menu Order',
            'menu.orders.store'                     => 'Save Menu Order',
            'menu.orders.show'                      => 'Show Menu Order',
            'menu.orders.edit'                      => 'Edit Menu Order',
            'menu.orders.update'                    => 'Update Menu Order',
            'menu.orders.destroy'                   => 'Delete Menu Order',
            'menu.orders.status'                    => 'Update Menu Order Status',

            'locations.qr-codes.index'              => 'View Location QR Codes',
            'locations.qr-codes.download'           => 'Download Location QR Code',
            'locations.qr-codes.download-all'       => 'Download All Location QR Codes',

            'locations.menu-assignment.index'       => 'View Location Menu Assignment',
            'locations.menu-assignment.save'        => 'Save Location Menu Assignment',
        ];

        $toNotBeDeleted = [];

        foreach ($permissions as $permission => $title) {
            $toNotBeDeleted[] = \Spatie\Permission\Models\Permission::updateOrCreate([
                'name' => $permission
            ],[
                'name'       => $permission,
                'guard_name' => 'web',
                'title'      => $title,
            ])->id;
        }

        if (!empty($toNotBeDeleted)) {
            \Spatie\Permission\Models\Permission::whereNotIn('id', $toNotBeDeleted)->delete();
            DB::table('model_has_permissions')->whereNotIn('permission_id', $toNotBeDeleted)->delete();
            DB::table('role_has_permissions')->whereNotIn('permission_id', $toNotBeDeleted)->delete();
        }
    }
}